# Generated by Django 5.1.6 on 2025-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_selected_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under18', 'Under 18'), ('18to24', '18-24'), ('25to34', '25-34'), ('35to44', '35-44'), ('45to54', '45-54'), ('55to64', '55-64'), ('65plus', '65 and Above')], max_length=10, null=True),
        ),
    ]
