# Generated by Django 5.1.6 on 2025-04-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age_group',
        ),
    ]
