# Generated by Django 5.1.6 on 2025-04-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
    ]
