# Generated by Django 5.1.6 on 2025-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_location_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Very Dissatisfied'), (2, '2 - Dissatisfied'), (3, '3 - Neutral'), (4, '4 - Satisfied'), (5, '5 - Very Satisfied')]),
        ),
    ]
